CREATE TABLE t_shedlock (
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT PK_SHEDLOCK
        PRIMARY KEY (name)
);
