#
# Copyright (c) 2020 Ubique Innovation AG <https://www.ubique.ch>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#

spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:prod}

management.endpoints.enabled-by-default: false

server:
  error.whitelabel.enabled: true
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/plain
      - text/xml
  http2:
    enabled: true
  port: ${SERVER_PORT:8080}


#-------------------------------------------------------------------------------
# JDBC Config
#-------------------------------------------------------------------------------
datasource:
  url: jdbc:postgresql://localhost:5432/dpppt
  username: dpppt
  password: dpppt
  driverClassName: org.postgresql.ds.PGSimpleDataSource

ws:
  exposedlist.cachecontrol: 5
  app.source: org.dpppt.demo
  headers:
    protected: X-HELLO,X-BATCH-RELEASE-TIME
    debug: true
