// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto
package org.dpppt.backend.sdk.model.gaen.proto;

public final class FileProto {
  private FileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:File)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>optional .Header header = 1;</code>
     */
    FileProto.Header getHeader();
    /**
     * <code>optional .Header header = 1;</code>
     */
    FileProto.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>repeated .Key key = 2;</code>
     */
    java.util.List<FileProto.Key> 
        getKeyList();
    /**
     * <code>repeated .Key key = 2;</code>
     */
    FileProto.Key getKey(int index);
    /**
     * <code>repeated .Key key = 2;</code>
     */
    int getKeyCount();
    /**
     * <code>repeated .Key key = 2;</code>
     */
    java.util.List<? extends FileProto.KeyOrBuilder> 
        getKeyOrBuilderList();
    /**
     * <code>repeated .Key key = 2;</code>
     */
    FileProto.KeyOrBuilder getKeyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code File}
   */
  public  static final class File extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:File)
      FileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use File.newBuilder() to construct.
    private File(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private File() {
      key_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private File(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              FileProto.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(FileProto.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                key_ = new java.util.ArrayList<FileProto.Key>();
                mutable_bitField0_ |= 0x00000002;
              }
              key_.add(
                  input.readMessage(FileProto.Key.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          key_ = java.util.Collections.unmodifiableList(key_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FileProto.internal_static_File_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FileProto.internal_static_File_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FileProto.File.class, FileProto.File.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private FileProto.Header header_;
    /**
     * <code>optional .Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .Header header = 1;</code>
     */
    public FileProto.Header getHeader() {
      return header_ == null ? FileProto.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>optional .Header header = 1;</code>
     */
    public FileProto.HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? FileProto.Header.getDefaultInstance() : header_;
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private java.util.List<FileProto.Key> key_;
    /**
     * <code>repeated .Key key = 2;</code>
     */
    public java.util.List<FileProto.Key> getKeyList() {
      return key_;
    }
    /**
     * <code>repeated .Key key = 2;</code>
     */
    public java.util.List<? extends FileProto.KeyOrBuilder> 
        getKeyOrBuilderList() {
      return key_;
    }
    /**
     * <code>repeated .Key key = 2;</code>
     */
    public int getKeyCount() {
      return key_.size();
    }
    /**
     * <code>repeated .Key key = 2;</code>
     */
    public FileProto.Key getKey(int index) {
      return key_.get(index);
    }
    /**
     * <code>repeated .Key key = 2;</code>
     */
    public FileProto.KeyOrBuilder getKeyOrBuilder(
        int index) {
      return key_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      for (int i = 0; i < key_.size(); i++) {
        output.writeMessage(2, key_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      for (int i = 0; i < key_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, key_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FileProto.File)) {
        return super.equals(obj);
      }
      FileProto.File other = (FileProto.File) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getKeyList()
          .equals(other.getKeyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (getKeyCount() > 0) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKeyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FileProto.File parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.File parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.File parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.File parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.File parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.File parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.File parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FileProto.File parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FileProto.File parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FileProto.File parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FileProto.File parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FileProto.File parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FileProto.File prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code File}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:File)
        FileProto.FileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FileProto.internal_static_File_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FileProto.internal_static_File_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FileProto.File.class, FileProto.File.Builder.class);
      }

      // Construct using FileOuterClass.File.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getKeyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (keyBuilder_ == null) {
          key_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          keyBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FileProto.internal_static_File_descriptor;
      }

      @java.lang.Override
      public FileProto.File getDefaultInstanceForType() {
        return FileProto.File.getDefaultInstance();
      }

      @java.lang.Override
      public FileProto.File build() {
        FileProto.File result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FileProto.File buildPartial() {
        FileProto.File result = new FileProto.File(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (headerBuilder_ == null) {
            result.header_ = header_;
          } else {
            result.header_ = headerBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (keyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            key_ = java.util.Collections.unmodifiableList(key_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.key_ = key_;
        } else {
          result.key_ = keyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FileProto.File) {
          return mergeFrom((FileProto.File)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FileProto.File other) {
        if (other == FileProto.File.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (keyBuilder_ == null) {
          if (!other.key_.isEmpty()) {
            if (key_.isEmpty()) {
              key_ = other.key_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureKeyIsMutable();
              key_.addAll(other.key_);
            }
            onChanged();
          }
        } else {
          if (!other.key_.isEmpty()) {
            if (keyBuilder_.isEmpty()) {
              keyBuilder_.dispose();
              keyBuilder_ = null;
              key_ = other.key_;
              bitField0_ = (bitField0_ & ~0x00000002);
              keyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKeyFieldBuilder() : null;
            } else {
              keyBuilder_.addAllMessages(other.key_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FileProto.File parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FileProto.File) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private FileProto.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          FileProto.Header, FileProto.Header.Builder, FileProto.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .Header header = 1;</code>
       */
      public FileProto.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? FileProto.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Header header = 1;</code>
       */
      public Builder setHeader(FileProto.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Header header = 1;</code>
       */
      public Builder setHeader(
          FileProto.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Header header = 1;</code>
       */
      public Builder mergeHeader(FileProto.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              header_ != null &&
              header_ != FileProto.Header.getDefaultInstance()) {
            header_ =
              FileProto.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Header header = 1;</code>
       */
      public FileProto.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Header header = 1;</code>
       */
      public FileProto.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              FileProto.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>optional .Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FileProto.Header, FileProto.Header.Builder, FileProto.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FileProto.Header, FileProto.Header.Builder, FileProto.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.util.List<FileProto.Key> key_ =
        java.util.Collections.emptyList();
      private void ensureKeyIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          key_ = new java.util.ArrayList<FileProto.Key>(key_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          FileProto.Key, FileProto.Key.Builder, FileProto.KeyOrBuilder> keyBuilder_;

      /**
       * <code>repeated .Key key = 2;</code>
       */
      public java.util.List<FileProto.Key> getKeyList() {
        if (keyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(key_);
        } else {
          return keyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public int getKeyCount() {
        if (keyBuilder_ == null) {
          return key_.size();
        } else {
          return keyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public FileProto.Key getKey(int index) {
        if (keyBuilder_ == null) {
          return key_.get(index);
        } else {
          return keyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder setKey(
          int index, FileProto.Key value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyIsMutable();
          key_.set(index, value);
          onChanged();
        } else {
          keyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder setKey(
          int index, FileProto.Key.Builder builderForValue) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          key_.set(index, builderForValue.build());
          onChanged();
        } else {
          keyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder addKey(FileProto.Key value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyIsMutable();
          key_.add(value);
          onChanged();
        } else {
          keyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder addKey(
          int index, FileProto.Key value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyIsMutable();
          key_.add(index, value);
          onChanged();
        } else {
          keyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder addKey(
          FileProto.Key.Builder builderForValue) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          key_.add(builderForValue.build());
          onChanged();
        } else {
          keyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder addKey(
          int index, FileProto.Key.Builder builderForValue) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          key_.add(index, builderForValue.build());
          onChanged();
        } else {
          keyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder addAllKey(
          java.lang.Iterable<? extends FileProto.Key> values) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, key_);
          onChanged();
        } else {
          keyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder clearKey() {
        if (keyBuilder_ == null) {
          key_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          keyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public Builder removeKey(int index) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          key_.remove(index);
          onChanged();
        } else {
          keyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public FileProto.Key.Builder getKeyBuilder(
          int index) {
        return getKeyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public FileProto.KeyOrBuilder getKeyOrBuilder(
          int index) {
        if (keyBuilder_ == null) {
          return key_.get(index);  } else {
          return keyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public java.util.List<? extends FileProto.KeyOrBuilder> 
           getKeyOrBuilderList() {
        if (keyBuilder_ != null) {
          return keyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(key_);
        }
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public FileProto.Key.Builder addKeyBuilder() {
        return getKeyFieldBuilder().addBuilder(
            FileProto.Key.getDefaultInstance());
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public FileProto.Key.Builder addKeyBuilder(
          int index) {
        return getKeyFieldBuilder().addBuilder(
            index, FileProto.Key.getDefaultInstance());
      }
      /**
       * <code>repeated .Key key = 2;</code>
       */
      public java.util.List<FileProto.Key.Builder> 
           getKeyBuilderList() {
        return getKeyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          FileProto.Key, FileProto.Key.Builder, FileProto.KeyOrBuilder> 
          getKeyFieldBuilder() {
        if (keyBuilder_ == null) {
          keyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              FileProto.Key, FileProto.Key.Builder, FileProto.KeyOrBuilder>(
                  key_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          key_ = null;
        }
        return keyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:File)
    }

    // @@protoc_insertion_point(class_scope:File)
    private static final FileProto.File DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FileProto.File();
    }

    public static FileProto.File getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<File>
        PARSER = new com.google.protobuf.AbstractParser<File>() {
      @java.lang.Override
      public File parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new File(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<File> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<File> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FileProto.File getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Time window of keys in this file based on arrival to server, in UTC.
     * </pre>
     *
     * <code>optional int64 startTimestamp = 1;</code>
     */
    boolean hasStartTimestamp();
    /**
     * <pre>
     * Time window of keys in this file based on arrival to server, in UTC.
     * </pre>
     *
     * <code>optional int64 startTimestamp = 1;</code>
     */
    long getStartTimestamp();

    /**
     * <code>optional int64 endTimestamp = 2;</code>
     */
    boolean hasEndTimestamp();
    /**
     * <code>optional int64 endTimestamp = 2;</code>
     */
    long getEndTimestamp();

    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    boolean hasRegion();
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    java.lang.String getRegion();
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    com.google.protobuf.ByteString
        getRegionBytes();

    /**
     * <pre>
     * E.g., Batch 2 of 10
     * </pre>
     *
     * <code>optional int32 batchNum = 4;</code>
     */
    boolean hasBatchNum();
    /**
     * <pre>
     * E.g., Batch 2 of 10
     * </pre>
     *
     * <code>optional int32 batchNum = 4;</code>
     */
    int getBatchNum();

    /**
     * <code>optional int32 batchSize = 5;</code>
     */
    boolean hasBatchSize();
    /**
     * <code>optional int32 batchSize = 5;</code>
     */
    int getBatchSize();
  }
  /**
   * Protobuf type {@code Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      region_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              startTimestamp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              endTimestamp_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              region_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              batchNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              batchSize_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FileProto.internal_static_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FileProto.internal_static_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FileProto.Header.class, FileProto.Header.Builder.class);
    }

    private int bitField0_;
    public static final int STARTTIMESTAMP_FIELD_NUMBER = 1;
    private long startTimestamp_;
    /**
     * <pre>
     * Time window of keys in this file based on arrival to server, in UTC.
     * </pre>
     *
     * <code>optional int64 startTimestamp = 1;</code>
     */
    public boolean hasStartTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Time window of keys in this file based on arrival to server, in UTC.
     * </pre>
     *
     * <code>optional int64 startTimestamp = 1;</code>
     */
    public long getStartTimestamp() {
      return startTimestamp_;
    }

    public static final int ENDTIMESTAMP_FIELD_NUMBER = 2;
    private long endTimestamp_;
    /**
     * <code>optional int64 endTimestamp = 2;</code>
     */
    public boolean hasEndTimestamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 endTimestamp = 2;</code>
     */
    public long getEndTimestamp() {
      return endTimestamp_;
    }

    public static final int REGION_FIELD_NUMBER = 3;
    private volatile java.lang.Object region_;
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          region_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATCHNUM_FIELD_NUMBER = 4;
    private int batchNum_;
    /**
     * <pre>
     * E.g., Batch 2 of 10
     * </pre>
     *
     * <code>optional int32 batchNum = 4;</code>
     */
    public boolean hasBatchNum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * E.g., Batch 2 of 10
     * </pre>
     *
     * <code>optional int32 batchNum = 4;</code>
     */
    public int getBatchNum() {
      return batchNum_;
    }

    public static final int BATCHSIZE_FIELD_NUMBER = 5;
    private int batchSize_;
    /**
     * <code>optional int32 batchSize = 5;</code>
     */
    public boolean hasBatchSize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 batchSize = 5;</code>
     */
    public int getBatchSize() {
      return batchSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, startTimestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, endTimestamp_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, region_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, batchNum_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, batchSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, startTimestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, endTimestamp_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, region_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, batchNum_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, batchSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FileProto.Header)) {
        return super.equals(obj);
      }
      FileProto.Header other = (FileProto.Header) obj;

      if (hasStartTimestamp() != other.hasStartTimestamp()) return false;
      if (hasStartTimestamp()) {
        if (getStartTimestamp()
            != other.getStartTimestamp()) return false;
      }
      if (hasEndTimestamp() != other.hasEndTimestamp()) return false;
      if (hasEndTimestamp()) {
        if (getEndTimestamp()
            != other.getEndTimestamp()) return false;
      }
      if (hasRegion() != other.hasRegion()) return false;
      if (hasRegion()) {
        if (!getRegion()
            .equals(other.getRegion())) return false;
      }
      if (hasBatchNum() != other.hasBatchNum()) return false;
      if (hasBatchNum()) {
        if (getBatchNum()
            != other.getBatchNum()) return false;
      }
      if (hasBatchSize() != other.hasBatchSize()) return false;
      if (hasBatchSize()) {
        if (getBatchSize()
            != other.getBatchSize()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStartTimestamp()) {
        hash = (37 * hash) + STARTTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTimestamp());
      }
      if (hasEndTimestamp()) {
        hash = (37 * hash) + ENDTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEndTimestamp());
      }
      if (hasRegion()) {
        hash = (37 * hash) + REGION_FIELD_NUMBER;
        hash = (53 * hash) + getRegion().hashCode();
      }
      if (hasBatchNum()) {
        hash = (37 * hash) + BATCHNUM_FIELD_NUMBER;
        hash = (53 * hash) + getBatchNum();
      }
      if (hasBatchSize()) {
        hash = (37 * hash) + BATCHSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getBatchSize();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FileProto.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FileProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FileProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FileProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FileProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FileProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FileProto.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Header)
        FileProto.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FileProto.internal_static_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FileProto.internal_static_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FileProto.Header.class, FileProto.Header.Builder.class);
      }

      // Construct using FileOuterClass.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        endTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        region_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        batchNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        batchSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FileProto.internal_static_Header_descriptor;
      }

      @java.lang.Override
      public FileProto.Header getDefaultInstanceForType() {
        return FileProto.Header.getDefaultInstance();
      }

      @java.lang.Override
      public FileProto.Header build() {
        FileProto.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FileProto.Header buildPartial() {
        FileProto.Header result = new FileProto.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.startTimestamp_ = startTimestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.endTimestamp_ = endTimestamp_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.region_ = region_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.batchNum_ = batchNum_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.batchSize_ = batchSize_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FileProto.Header) {
          return mergeFrom((FileProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FileProto.Header other) {
        if (other == FileProto.Header.getDefaultInstance()) return this;
        if (other.hasStartTimestamp()) {
          setStartTimestamp(other.getStartTimestamp());
        }
        if (other.hasEndTimestamp()) {
          setEndTimestamp(other.getEndTimestamp());
        }
        if (other.hasRegion()) {
          bitField0_ |= 0x00000004;
          region_ = other.region_;
          onChanged();
        }
        if (other.hasBatchNum()) {
          setBatchNum(other.getBatchNum());
        }
        if (other.hasBatchSize()) {
          setBatchSize(other.getBatchSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FileProto.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FileProto.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long startTimestamp_ ;
      /**
       * <pre>
       * Time window of keys in this file based on arrival to server, in UTC.
       * </pre>
       *
       * <code>optional int64 startTimestamp = 1;</code>
       */
      public boolean hasStartTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Time window of keys in this file based on arrival to server, in UTC.
       * </pre>
       *
       * <code>optional int64 startTimestamp = 1;</code>
       */
      public long getStartTimestamp() {
        return startTimestamp_;
      }
      /**
       * <pre>
       * Time window of keys in this file based on arrival to server, in UTC.
       * </pre>
       *
       * <code>optional int64 startTimestamp = 1;</code>
       */
      public Builder setStartTimestamp(long value) {
        bitField0_ |= 0x00000001;
        startTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time window of keys in this file based on arrival to server, in UTC.
       * </pre>
       *
       * <code>optional int64 startTimestamp = 1;</code>
       */
      public Builder clearStartTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private long endTimestamp_ ;
      /**
       * <code>optional int64 endTimestamp = 2;</code>
       */
      public boolean hasEndTimestamp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 endTimestamp = 2;</code>
       */
      public long getEndTimestamp() {
        return endTimestamp_;
      }
      /**
       * <code>optional int64 endTimestamp = 2;</code>
       */
      public Builder setEndTimestamp(long value) {
        bitField0_ |= 0x00000002;
        endTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 endTimestamp = 2;</code>
       */
      public Builder clearEndTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object region_ = "";
      /**
       * <pre>
       * Region for which these keys came from (e.g., country)
       * </pre>
       *
       * <code>optional string region = 3;</code>
       */
      public boolean hasRegion() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Region for which these keys came from (e.g., country)
       * </pre>
       *
       * <code>optional string region = 3;</code>
       */
      public java.lang.String getRegion() {
        java.lang.Object ref = region_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            region_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Region for which these keys came from (e.g., country)
       * </pre>
       *
       * <code>optional string region = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRegionBytes() {
        java.lang.Object ref = region_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          region_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Region for which these keys came from (e.g., country)
       * </pre>
       *
       * <code>optional string region = 3;</code>
       */
      public Builder setRegion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Region for which these keys came from (e.g., country)
       * </pre>
       *
       * <code>optional string region = 3;</code>
       */
      public Builder clearRegion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        region_ = getDefaultInstance().getRegion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Region for which these keys came from (e.g., country)
       * </pre>
       *
       * <code>optional string region = 3;</code>
       */
      public Builder setRegionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        region_ = value;
        onChanged();
        return this;
      }

      private int batchNum_ ;
      /**
       * <pre>
       * E.g., Batch 2 of 10
       * </pre>
       *
       * <code>optional int32 batchNum = 4;</code>
       */
      public boolean hasBatchNum() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * E.g., Batch 2 of 10
       * </pre>
       *
       * <code>optional int32 batchNum = 4;</code>
       */
      public int getBatchNum() {
        return batchNum_;
      }
      /**
       * <pre>
       * E.g., Batch 2 of 10
       * </pre>
       *
       * <code>optional int32 batchNum = 4;</code>
       */
      public Builder setBatchNum(int value) {
        bitField0_ |= 0x00000008;
        batchNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * E.g., Batch 2 of 10
       * </pre>
       *
       * <code>optional int32 batchNum = 4;</code>
       */
      public Builder clearBatchNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batchNum_ = 0;
        onChanged();
        return this;
      }

      private int batchSize_ ;
      /**
       * <code>optional int32 batchSize = 5;</code>
       */
      public boolean hasBatchSize() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 batchSize = 5;</code>
       */
      public int getBatchSize() {
        return batchSize_;
      }
      /**
       * <code>optional int32 batchSize = 5;</code>
       */
      public Builder setBatchSize(int value) {
        bitField0_ |= 0x00000010;
        batchSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 batchSize = 5;</code>
       */
      public Builder clearBatchSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        batchSize_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Header)
    }

    // @@protoc_insertion_point(class_scope:Header)
    private static final FileProto.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FileProto.Header();
    }

    public static FileProto.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @java.lang.Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FileProto.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Key)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Key of infected user
     * </pre>
     *
     * <code>optional bytes keyData = 1;</code>
     */
    boolean hasKeyData();
    /**
     * <pre>
     * Key of infected user
     * </pre>
     *
     * <code>optional bytes keyData = 1;</code>
     */
    com.google.protobuf.ByteString getKeyData();

    /**
     * <pre>
     * Interval number when the key's EKRollingPeriod started.
     * </pre>
     *
     * <code>optional uint32 rollingStartNumber = 2;</code>
     */
    boolean hasRollingStartNumber();
    /**
     * <pre>
     * Interval number when the key's EKRollingPeriod started.
     * </pre>
     *
     * <code>optional uint32 rollingStartNumber = 2;</code>
     */
    int getRollingStartNumber();

    /**
     * <pre>
     * Number of 10-minute windows between key rolling.
     * </pre>
     *
     * <code>optional uint32 rollingPeriod = 3;</code>
     */
    boolean hasRollingPeriod();
    /**
     * <pre>
     * Number of 10-minute windows between key rolling.
     * </pre>
     *
     * <code>optional uint32 rollingPeriod = 3;</code>
     */
    int getRollingPeriod();

    /**
     * <pre>
     * Risk of transmission associated with the person this key came from.
     * </pre>
     *
     * <code>optional int32 transmissionRiskLevel = 4;</code>
     */
    boolean hasTransmissionRiskLevel();
    /**
     * <pre>
     * Risk of transmission associated with the person this key came from.
     * </pre>
     *
     * <code>optional int32 transmissionRiskLevel = 4;</code>
     */
    int getTransmissionRiskLevel();
  }
  /**
   * Protobuf type {@code Key}
   */
  public  static final class Key extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Key)
      KeyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Key.newBuilder() to construct.
    private Key(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Key() {
      keyData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Key(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              keyData_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rollingStartNumber_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rollingPeriod_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              transmissionRiskLevel_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FileProto.internal_static_Key_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FileProto.internal_static_Key_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FileProto.Key.class, FileProto.Key.Builder.class);
    }

    private int bitField0_;
    public static final int KEYDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString keyData_;
    /**
     * <pre>
     * Key of infected user
     * </pre>
     *
     * <code>optional bytes keyData = 1;</code>
     */
    public boolean hasKeyData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Key of infected user
     * </pre>
     *
     * <code>optional bytes keyData = 1;</code>
     */
    public com.google.protobuf.ByteString getKeyData() {
      return keyData_;
    }

    public static final int ROLLINGSTARTNUMBER_FIELD_NUMBER = 2;
    private int rollingStartNumber_;
    /**
     * <pre>
     * Interval number when the key's EKRollingPeriod started.
     * </pre>
     *
     * <code>optional uint32 rollingStartNumber = 2;</code>
     */
    public boolean hasRollingStartNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Interval number when the key's EKRollingPeriod started.
     * </pre>
     *
     * <code>optional uint32 rollingStartNumber = 2;</code>
     */
    public int getRollingStartNumber() {
      return rollingStartNumber_;
    }

    public static final int ROLLINGPERIOD_FIELD_NUMBER = 3;
    private int rollingPeriod_;
    /**
     * <pre>
     * Number of 10-minute windows between key rolling.
     * </pre>
     *
     * <code>optional uint32 rollingPeriod = 3;</code>
     */
    public boolean hasRollingPeriod() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Number of 10-minute windows between key rolling.
     * </pre>
     *
     * <code>optional uint32 rollingPeriod = 3;</code>
     */
    public int getRollingPeriod() {
      return rollingPeriod_;
    }

    public static final int TRANSMISSIONRISKLEVEL_FIELD_NUMBER = 4;
    private int transmissionRiskLevel_;
    /**
     * <pre>
     * Risk of transmission associated with the person this key came from.
     * </pre>
     *
     * <code>optional int32 transmissionRiskLevel = 4;</code>
     */
    public boolean hasTransmissionRiskLevel() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Risk of transmission associated with the person this key came from.
     * </pre>
     *
     * <code>optional int32 transmissionRiskLevel = 4;</code>
     */
    public int getTransmissionRiskLevel() {
      return transmissionRiskLevel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, keyData_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, rollingStartNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, rollingPeriod_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, transmissionRiskLevel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, keyData_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, rollingStartNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, rollingPeriod_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, transmissionRiskLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FileProto.Key)) {
        return super.equals(obj);
      }
      FileProto.Key other = (FileProto.Key) obj;

      if (hasKeyData() != other.hasKeyData()) return false;
      if (hasKeyData()) {
        if (!getKeyData()
            .equals(other.getKeyData())) return false;
      }
      if (hasRollingStartNumber() != other.hasRollingStartNumber()) return false;
      if (hasRollingStartNumber()) {
        if (getRollingStartNumber()
            != other.getRollingStartNumber()) return false;
      }
      if (hasRollingPeriod() != other.hasRollingPeriod()) return false;
      if (hasRollingPeriod()) {
        if (getRollingPeriod()
            != other.getRollingPeriod()) return false;
      }
      if (hasTransmissionRiskLevel() != other.hasTransmissionRiskLevel()) return false;
      if (hasTransmissionRiskLevel()) {
        if (getTransmissionRiskLevel()
            != other.getTransmissionRiskLevel()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasKeyData()) {
        hash = (37 * hash) + KEYDATA_FIELD_NUMBER;
        hash = (53 * hash) + getKeyData().hashCode();
      }
      if (hasRollingStartNumber()) {
        hash = (37 * hash) + ROLLINGSTARTNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getRollingStartNumber();
      }
      if (hasRollingPeriod()) {
        hash = (37 * hash) + ROLLINGPERIOD_FIELD_NUMBER;
        hash = (53 * hash) + getRollingPeriod();
      }
      if (hasTransmissionRiskLevel()) {
        hash = (37 * hash) + TRANSMISSIONRISKLEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getTransmissionRiskLevel();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FileProto.Key parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.Key parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.Key parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.Key parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.Key parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileProto.Key parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileProto.Key parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FileProto.Key parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FileProto.Key parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FileProto.Key parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FileProto.Key parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FileProto.Key parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FileProto.Key prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Key}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Key)
        FileProto.KeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FileProto.internal_static_Key_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FileProto.internal_static_Key_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FileProto.Key.class, FileProto.Key.Builder.class);
      }

      // Construct using FileOuterClass.Key.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        keyData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        rollingStartNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rollingPeriod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        transmissionRiskLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FileProto.internal_static_Key_descriptor;
      }

      @java.lang.Override
      public FileProto.Key getDefaultInstanceForType() {
        return FileProto.Key.getDefaultInstance();
      }

      @java.lang.Override
      public FileProto.Key build() {
        FileProto.Key result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FileProto.Key buildPartial() {
        FileProto.Key result = new FileProto.Key(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyData_ = keyData_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rollingStartNumber_ = rollingStartNumber_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.rollingPeriod_ = rollingPeriod_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.transmissionRiskLevel_ = transmissionRiskLevel_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FileProto.Key) {
          return mergeFrom((FileProto.Key)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FileProto.Key other) {
        if (other == FileProto.Key.getDefaultInstance()) return this;
        if (other.hasKeyData()) {
          setKeyData(other.getKeyData());
        }
        if (other.hasRollingStartNumber()) {
          setRollingStartNumber(other.getRollingStartNumber());
        }
        if (other.hasRollingPeriod()) {
          setRollingPeriod(other.getRollingPeriod());
        }
        if (other.hasTransmissionRiskLevel()) {
          setTransmissionRiskLevel(other.getTransmissionRiskLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FileProto.Key parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FileProto.Key) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString keyData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Key of infected user
       * </pre>
       *
       * <code>optional bytes keyData = 1;</code>
       */
      public boolean hasKeyData() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Key of infected user
       * </pre>
       *
       * <code>optional bytes keyData = 1;</code>
       */
      public com.google.protobuf.ByteString getKeyData() {
        return keyData_;
      }
      /**
       * <pre>
       * Key of infected user
       * </pre>
       *
       * <code>optional bytes keyData = 1;</code>
       */
      public Builder setKeyData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        keyData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Key of infected user
       * </pre>
       *
       * <code>optional bytes keyData = 1;</code>
       */
      public Builder clearKeyData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyData_ = getDefaultInstance().getKeyData();
        onChanged();
        return this;
      }

      private int rollingStartNumber_ ;
      /**
       * <pre>
       * Interval number when the key's EKRollingPeriod started.
       * </pre>
       *
       * <code>optional uint32 rollingStartNumber = 2;</code>
       */
      public boolean hasRollingStartNumber() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Interval number when the key's EKRollingPeriod started.
       * </pre>
       *
       * <code>optional uint32 rollingStartNumber = 2;</code>
       */
      public int getRollingStartNumber() {
        return rollingStartNumber_;
      }
      /**
       * <pre>
       * Interval number when the key's EKRollingPeriod started.
       * </pre>
       *
       * <code>optional uint32 rollingStartNumber = 2;</code>
       */
      public Builder setRollingStartNumber(int value) {
        bitField0_ |= 0x00000002;
        rollingStartNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Interval number when the key's EKRollingPeriod started.
       * </pre>
       *
       * <code>optional uint32 rollingStartNumber = 2;</code>
       */
      public Builder clearRollingStartNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rollingStartNumber_ = 0;
        onChanged();
        return this;
      }

      private int rollingPeriod_ ;
      /**
       * <pre>
       * Number of 10-minute windows between key rolling.
       * </pre>
       *
       * <code>optional uint32 rollingPeriod = 3;</code>
       */
      public boolean hasRollingPeriod() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Number of 10-minute windows between key rolling.
       * </pre>
       *
       * <code>optional uint32 rollingPeriod = 3;</code>
       */
      public int getRollingPeriod() {
        return rollingPeriod_;
      }
      /**
       * <pre>
       * Number of 10-minute windows between key rolling.
       * </pre>
       *
       * <code>optional uint32 rollingPeriod = 3;</code>
       */
      public Builder setRollingPeriod(int value) {
        bitField0_ |= 0x00000004;
        rollingPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of 10-minute windows between key rolling.
       * </pre>
       *
       * <code>optional uint32 rollingPeriod = 3;</code>
       */
      public Builder clearRollingPeriod() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rollingPeriod_ = 0;
        onChanged();
        return this;
      }

      private int transmissionRiskLevel_ ;
      /**
       * <pre>
       * Risk of transmission associated with the person this key came from.
       * </pre>
       *
       * <code>optional int32 transmissionRiskLevel = 4;</code>
       */
      public boolean hasTransmissionRiskLevel() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Risk of transmission associated with the person this key came from.
       * </pre>
       *
       * <code>optional int32 transmissionRiskLevel = 4;</code>
       */
      public int getTransmissionRiskLevel() {
        return transmissionRiskLevel_;
      }
      /**
       * <pre>
       * Risk of transmission associated with the person this key came from.
       * </pre>
       *
       * <code>optional int32 transmissionRiskLevel = 4;</code>
       */
      public Builder setTransmissionRiskLevel(int value) {
        bitField0_ |= 0x00000008;
        transmissionRiskLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Risk of transmission associated with the person this key came from.
       * </pre>
       *
       * <code>optional int32 transmissionRiskLevel = 4;</code>
       */
      public Builder clearTransmissionRiskLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        transmissionRiskLevel_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Key)
    }

    // @@protoc_insertion_point(class_scope:Key)
    private static final FileProto.Key DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FileProto.Key();
    }

    public static FileProto.Key getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Key>
        PARSER = new com.google.protobuf.AbstractParser<Key>() {
      @java.lang.Override
      public Key parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Key(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Key> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Key> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FileProto.Key getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_File_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_File_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Key_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\"2\n\004File\022\027\n\006header\030\001 \001(\0132\007.H" +
      "eader\022\021\n\003key\030\002 \003(\0132\004.Key\"k\n\006Header\022\026\n\016st" +
      "artTimestamp\030\001 \001(\003\022\024\n\014endTimestamp\030\002 \001(\003" +
      "\022\016\n\006region\030\003 \001(\t\022\020\n\010batchNum\030\004 \001(\005\022\021\n\tba" +
      "tchSize\030\005 \001(\005\"h\n\003Key\022\017\n\007keyData\030\001 \001(\014\022\032\n" +
      "\022rollingStartNumber\030\002 \001(\r\022\025\n\rrollingPeri" +
      "od\030\003 \001(\r\022\035\n\025transmissionRiskLevel\030\004 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_File_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_File_descriptor,
        new java.lang.String[] { "Header", "Key", });
    internal_static_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Header_descriptor,
        new java.lang.String[] { "StartTimestamp", "EndTimestamp", "Region", "BatchNum", "BatchSize", });
    internal_static_Key_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Key_descriptor,
        new java.lang.String[] { "KeyData", "RollingStartNumber", "RollingPeriod", "TransmissionRiskLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
