version: '3.1'

services:

  dpppt_db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: dpppt
      POSTGRES_DB: dpppt
      POSTGRES_USER: dpppt
    ports:
      - "5432:5432"
    volumes:
      - dpppt_db_data:/var/lib/postgresql/data
volumes:
  dpppt_db_data:
