openapi: 3.0.0
servers:
- url: https://demo.dpppt.org
  description: ''
info:
  version: 1.0-gapple
  description: DP3T API
  title: DP3T API
paths:
  /v1/exposed:
    post:
      summary: addExposee
      description: Send exposed key to server
      responses:
        '200':
          description: The exposed keys have been stored in the database
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid base64 encoding in expose request
        '403':
          description: Authentication failed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposeeRequest'
        description: The ExposeeRequest contains the SecretKey from the guessed infection
          date, the infection date itself, and some authentication data to verify
          the test result
      parameters:
      - name: User-Agent
        in: header
        description: App Identifier (PackageName/BundleIdentifier) + App-Version +
          OS (Android/iOS) + OS-Version
        example: ch.ubique.android.starsdk;1.0;iOS;13.3
        required: true
        schema:
          type: string
  /v1/:
    get:
      summary: hello
      description: Hello return
      responses:
        '200':
          description: server live
          content:
            application/json:
              schema:
                type: string
  /v1/exposedlist:
    post:
      summary: addExposee
      description: Send a list of exposed keys to server
      responses:
        '200':
          description: The exposed keys have been stored in the database
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid base64 encoding in exposee request
        '403':
          description: Authentication failed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposeeRequestList'
        description: The ExposeeRequest contains the SecretKey from the guessed infection
          date, the infection date itself, and some authentication data to verify
          the test result
      parameters:
      - name: User-Agent
        in: header
        description: App Identifier (PackageName/BundleIdentifier) + App-Version +
          OS (Android/iOS) + OS-Version
        example: ch.ubique.android.starsdk;1.0;iOS;13.3
        required: true
        schema:
          type: string
  /v1/exposedjson/{batchReleaseTime}:
    get:
      summary: getExposedByDayDate
      description: Query list of exposed keys from a specific batch release time
      responses:
        '200':
          description: Returns ExposedOverview in json format, which includes all
            exposed keys which were published on _batchReleaseTime_
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposedOverview'
        '404':
          description: Couldn't find _batchReleaseTime_
      parameters:
      - name: batchReleaseTime
        in: path
        description: The batch release date of the exposed keys in milliseconds since
          Unix Epoch (1970-01-01), must be a multiple of 2 * 60 * 60 * 1000
        example: '1593043200000'
        required: true
        schema:
          type: integer
          format: long
  /v1/exposed/{batchReleaseTime}:
    get:
      summary: getExposedByBatch
      description: Query list of exposed keys from a specific batch release time
      responses:
        '200':
          description: Returns ExposedOverview in protobuf format, which includes
            all exposed keys which were published on _batchReleaseTime_
          content:
            application/x-protobuf:
              schema:
                $ref: '#/components/schemas/org.dpppt.backend.sdk.model.proto.Exposed.ProtoExposedList'
        '404':
          description: Couldn't find _batchReleaseTime_
      parameters:
      - name: batchReleaseTime
        in: path
        description: The batch release date of the exposed keys in milliseconds since
          Unix Epoch (1970-01-01), must be a multiple of 2 * 60 * 60 * 1000
        example: '1593043200000'
        required: true
        schema:
          type: integer
          format: long
  /v1/buckets/{dayDateStr}:
    get:
      summary: getListOfBuckets
      description: Query number of available buckets in a given day, starting from
        midnight UTC
      responses:
        '200':
          description: Returns BucketList in json format, indicating all available
            buckets since _dayDateStr_
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/org.dpppt.backend.sdk.model.BucketList'
      parameters:
      - name: dayDateStr
        in: path
        description: The date starting when to return the available buckets, in ISO8601
          date format
        example: '2019-01-31'
        required: true
        schema:
          type: string
  /v1/gaen/exposed:
    post:
      summary: addExposed
      description: addExposed
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/org.dpppt.backend.sdk.model.gaen.GaenRequest'
        description: N/A
      parameters:
      - name: User-Agent
        in: header
        description: ''
        required: true
        schema:
          type: string
  /v1/gaen/exposednextday:
    post:
      summary: addExposedSecond
      description: addExposedSecond
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/org.dpppt.backend.sdk.model.gaen.GaenSecondDay'
        description: N/A
      parameters:
      - name: User-Agent
        in: header
        description: ''
        required: true
        schema:
          type: string
  /v1/gaen/exposed/{keyDate}:
    get:
      summary: getExposedKeys
      description: getExposedKeys
      responses:
        '200':
          description: ''
          content:
            application/zip:
              schema:
                type: string
                format: binary
      parameters:
      - name: keyDate
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: long
      - name: publishedafter
        in: query
        description: ''
        required: false
        schema:
          type: integer
          format: long
  /v1/gaen/exposedjson/{keyDate}:
    get:
      summary: getExposedKeysAsJson
      description: getExposedKeysAsJson
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/org.dpppt.backend.sdk.model.gaen.GaenExposedJson'
      parameters:
      - name: keyDate
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: long
      - name: publishedafter
        in: query
        description: ''
        required: false
        schema:
          type: integer
          format: long
  /v1/gaen/buckets/{dayDateStr}:
    get:
      summary: getBuckets
      description: getBuckets
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/org.dpppt.backend.sdk.model.gaen.DayBuckets'
      parameters:
      - name: dayDateStr
        in: path
        description: ''
        required: true
        schema:
          type: string
components:
  schemas:
    org.dpppt.backend.sdk.model.BucketList:
      type: object
      properties:
        buckets:
          type: array
          items:
            type: integer
    org.dpppt.backend.sdk.model.ExposedKey:
      type: object
      required:
      - key
      - keyDate
      properties:
        key:
          type: string
        keyDate:
          type: integer
          format: long
    org.dpppt.backend.sdk.model.ExposedOverview:
      type: object
      properties:
        batchReleaseTime:
          type: integer
          format: long
        exposed:
          type: array
          items:
            $ref: '#/components/schemas/org.dpppt.backend.sdk.model.Exposee'
    org.dpppt.backend.sdk.model.Exposee:
      type: object
      required:
      - key
      - keyDate
      properties:
        key:
          type: string
        keyDate:
          type: integer
          format: long
    org.dpppt.backend.sdk.model.ExposeeAuthData:
      type: object
      properties:
        value:
          type: string
    org.dpppt.backend.sdk.model.ExposeeRequest:
      type: object
      required:
      - key
      - keyDate
      properties:
        fake:
          type: integer
        key:
          type: string
        keyDate:
          type: integer
          format: long
        authData:
          $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposeeAuthData'
    org.dpppt.backend.sdk.model.ExposeeRequestList:
      type: object
      required:
      - exposedKeys
      properties:
        exposedKeys:
          type: array
          items:
            $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposedKey'
        fake:
          type: integer
    org.dpppt.backend.sdk.model.gaen.DayBuckets:
      type: object
      properties:
        dayTimestamp:
          type: integer
          format: long
        day:
          type: string
        relativeUrls:
          type: array
          items:
            type: string
    org.dpppt.backend.sdk.model.gaen.GaenExposedJson:
      type: object
      required:
      - gaenKeys
      properties:
        gaenKeys:
          type: array
          items:
            $ref: '#/components/schemas/org.dpppt.backend.sdk.model.gaen.GaenKey'
        header:
          $ref: '#/components/schemas/org.dpppt.backend.sdk.model.gaen.Header'
    org.dpppt.backend.sdk.model.gaen.GaenKey:
      type: object
      required:
      - keyData
      - rollingStartNumber
      - rollingPeriod
      - transmissionRiskLevel
      properties:
        keyData:
          type: string
        rollingStartNumber:
          type: integer
        rollingPeriod:
          type: integer
        transmissionRiskLevel:
          type: integer
        fake:
          type: integer
    org.dpppt.backend.sdk.model.gaen.GaenRequest:
      type: object
      required:
      - gaenKeys
      - delayedKeyDate
      properties:
        gaenKeys:
          type: array
          items:
            $ref: '#/components/schemas/org.dpppt.backend.sdk.model.gaen.GaenKey'
        delayedKeyDate:
          type: integer
    org.dpppt.backend.sdk.model.gaen.GaenSecondDay:
      type: object
      required:
      - delayedKey
      properties:
        delayedKey:
          $ref: '#/components/schemas/org.dpppt.backend.sdk.model.gaen.GaenKey'
    org.dpppt.backend.sdk.model.gaen.Header:
      type: object
      properties:
        startTimestamp:
          type: integer
          format: long
        endTimestamp:
          type: integer
          format: long
        region:
          type: string
        batchNum:
          type: integer
        batchSize:
          type: integer
    org.dpppt.backend.sdk.model.proto.Exposed.ProtoExposedList:
      type: object
      properties:
        bitField0_:
          type: integer
        batchReleaseTime_:
          type: integer
          format: long
        exposed_:
          type: array
          items:
            $ref: '#/components/schemas/org.dpppt.backend.sdk.model.proto.Exposed.ProtoExposee'
        memoizedSize:
          type: integer
        memoizedHashCode:
          type: integer
    org.dpppt.backend.sdk.model.proto.Exposed.ProtoExposee:
      type: object
      properties:
        keyDate_:
          type: integer
          format: long
        memoizedSize:
          type: integer
        memoizedHashCode:
          type: integer
