openapi: 3.0.0
servers:
- url: https://demo.dpppt.org
  description: ''
info:
  version: 1.0-develop
  description: DP3T API
  title: DP3T API
paths:
  /v1/:
    get:
      summary: hello
      description: hello
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
  /v1/exposed:
    post:
      summary: addExposee
      description: addExposee
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposeeRequest'
        description: N/A
      parameters:
      - name: User-Agent
        in: header
        description: ''
        required: true
        schema:
          type: string
  /v1/hashtest/{dayDateStr}:
    get:
      summary: getExposed
      description: getExposed
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposedOverview'
      parameters:
      - name: dayDateStr
        in: path
        description: ''
        required: true
        schema:
          type: string
  /v1/exposedjson/{batchReleaseTime}:
    get:
      summary: getExposedByDayDate
      description: getExposedByDayDate
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposedOverview'
      parameters:
      - name: batchReleaseTime
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: long
  /v1/exposed/{batchReleaseTime}:
    get:
      summary: getExposedByBatch
      description: getExposedByBatch
      responses:
        '200':
          description: ''
          content:
            application/x-protobuf:
              schema:
                $ref: '#/components/schemas/org.dpppt.backend.sdk.model.proto.Exposed.ProtoExposedList'
      parameters:
      - name: batchReleaseTime
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: long
components:
  schemas:
    org.dpppt.backend.sdk.model.ExposedOverview:
      type: object
      properties:
        batchReleaseTime:
          type: integer
          format: long
        exposed:
          type: array
          items:
            $ref: '#/components/schemas/org.dpppt.backend.sdk.model.Exposee'
    org.dpppt.backend.sdk.model.Exposee:
      type: object
      required:
      - key
      - keyDate
      properties:
        key:
          type: string
        keyDate:
          type: integer
          format: long
    org.dpppt.backend.sdk.model.ExposeeAuthData:
      type: object
      properties:
        value:
          type: string
    org.dpppt.backend.sdk.model.ExposeeRequest:
      type: object
      required:
      - key
      - keyDate
      properties:
        key:
          type: string
        keyDate:
          type: integer
          format: long
        authData:
          $ref: '#/components/schemas/org.dpppt.backend.sdk.model.ExposeeAuthData'
    org.dpppt.backend.sdk.model.proto.Exposed.ProtoExposedList:
      type: object
      properties:
        bitField0_:
          type: integer
        batchReleaseTime_:
          type: integer
          format: long
        exposed_:
          type: array
          items:
            $ref: '#/components/schemas/org.dpppt.backend.sdk.model.proto.Exposed.ProtoExposee'
        memoizedIsInitialized:
          $ref: '#/components/schemas/byte'
        unknownFields:
          $ref: '#/components/schemas/com.google.protobuf.UnknownFieldSet'
        memoizedSize:
          type: integer
        memoizedHashCode:
          type: integer
    org.dpppt.backend.sdk.model.proto.Exposed.ProtoExposee:
      type: object
      properties:
        key_:
          $ref: '#/components/schemas/com.google.protobuf.ByteString'
        keyDate_:
          type: integer
          format: long
        memoizedIsInitialized:
          $ref: '#/components/schemas/byte'
        unknownFields:
          $ref: '#/components/schemas/com.google.protobuf.UnknownFieldSet'
        memoizedSize:
          type: integer
        memoizedHashCode:
          type: integer
