name: pre-commit

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: pre-commit/action@v2.0.0
